name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, staging]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_EVENT_NAME: ${{ github.event_name }}
      GITHUB_TOKEN: ${{ secrets.LAMIN_BUILD_DOCS }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    strategy:
      fail-fast: false
      matrix:
        group: [unit, tasks]
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install git+https://github.com/laminlabs/laminci
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - run: nox -s lint
      - run: uv pip install --system -e .[dev]
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.group == 'tasks'
        env:
          LAMIN_API_KEY: ${{ secrets.LAMIN_API_KEY_TESTUSER1 }}
        run: lamin login && lamin connect laminlabs/lamindata
      - run: nox -s "test(group='${{ matrix.group }}')"
